sudo: required

os:
  - linux
  - osx

language: c

services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux:2017-GA
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; docker pull ubuntu:16.04; fi

script:
  - docker run --net=host -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd' -d microsoft/mssql-server-linux:2017-latest
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; docker build . --tag stack-test && docker run --net=host -w /odbc stack-test:latest stack test; fi
