sudo: required

language: c

services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux:2017-GA
  - docker pull ubuntu:16.04

script:
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd' -net=host -d microsoft/mssql-server-linux:2017-latest
  - docker build . --tag stack-test
  - docker run -net=host -w /odbc stack-test:latest stack test
