sudo: required

os:
  - linux

language: c

services:
  - docker

before_install:
  # Linux
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then docker pull ubuntu:16.04; fi

script:
  # Both Linux and OS X
  - docker run --net=host -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd' -d microsoft/mssql-server-linux:2017-latest
  # Linux
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then docker build . --tag stack-test && docker run --net=host -w /odbc stack-test:latest stack test; fi
